version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:317968578233:task-definition/Ecstaskdefinition-codedeploy:1"
        LoadBalancerInfo:
          ContainerName: "swiggy"
          ContainerPort: 3000
