# Google Cloud Build cloudbuild.yaml
steps:
  # Install dependencies
  # - name: 'python:3.11'
  # - name: 'amazoncorretto:17'
  

  # Run linting
  - name: 'google/cloud-sdk:latest'
    secretEnv: ['SONAR_TOKEN','PROJECT_ID','NVD_API_KEY']
    script: |
      echo "Installing dependencies..."
      python3 --version
      java -version
      export DEBIAN_FRONTEND=noninteractive
      apt-get install wget unzip -y
      curl -fsSL https://get.docker.com -o get-docker.sh
      sh get-docker.sh
      docker version
      echo "Performing Trivy file scan before building the image..."
      wget https://github.com/aquasecurity/trivy/releases/download/v0.19.2/trivy_0.19.2_Linux-64bit.tar.gz
      tar zxvf trivy_0.19.2_Linux-64bit.tar.gz
      export PATH=$PATH:$PWD
      trivy filesystem --exit-code 0 --no-progress . >> trivyfilescan.txt
      echo "Downloading and installing OWASP Dependency-Check..."
      wget https://github.com/dependency-check/DependencyCheck/releases/download/v12.1.0/dependency-check-12.1.0-release.zip
      unzip dependency-check-12.1.0-release.zip
      export SONAR_SCANNER_VERSION=4.7.0.2747
      export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
      curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
      unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
      export PATH=$SONAR_SCANNER_HOME/bin:$PATH
      export SONAR_SCANNER_OPTS="-server"
      ##########################################################################################################################################################################################
      echo "Building Docker image and pushing to artifact registry..."
      docker build -t "asia-south1-docker.pkg.dev/$PROJECT_ID/cicdrepository17042026/swiggy:latest" .
      docker push "asia-south1-docker.pkg.dev/$PROJECT_ID/cicdrepository17042026/swiggy:latest"
      ##########################################################################################################################################################################################
      echo "Performing Trivy image scan after building the image..." 
      trivy image  "asia-south1-docker.pkg.dev/$PROJECT_ID/cicdrepository17042026/swiggy:latest" >> trivyimage.txt
      # cat trivyimage.txt
      echo "Running OWASP Dependency-Check scan..."
      cd dependency-check/bin
      ./dependency-check.sh --scan . --nvdApiKey $NVD_API_KEY --format ALL 
      echo "Build completed successfully!"
      echo "Running SonarQube analysis result"
      sonar-scanner -Dsonar.projectKey=swiggy -Dsonar.sources=. -Dsonar.host.url=http://35.200.155.10:9000
      
availableSecrets:
  secretManager:
  - versionName: projects/196053730058/secrets/sonarqube_token/versions/1
    env: 'SONAR_TOKEN'  
  - versionName: projects/196053730058/secrets/nvd_api/versions/1
    env: 'NVD_API_KEY'
  - versionName: projects/196053730058/secrets/projectID/versions/1
    env: 'PROJECT_ID'

options:
  logging: CLOUD_LOGGING_ONLY
